name: local_course_player
description: A simple local course player (Option 2) - pick folder, sections, playlist, subtitles toggle
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  chewie: ^1.6.4
  path: ^1.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
